from enum import Enum

DEFAULT_AGENT_PORT = 8765
DEFAULT_DISCOVERY_PORT = 8766
DISCOVERY_MAGIC_REQUEST = "LAN_CONTROL_DISCOVERY_REQ"
DISCOVERY_MAGIC_RESPONSE = "LAN_CONTROL_DISCOVERY_RESP"
AUTH_HEADER_NAME = "X-Agent-Token"
PROTOCOL_VERSION = "1.0.0"
API_V1_PREFIX = "/api/v1"


class ErrorCode(str, Enum):
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_ACTION = "INVALID_ACTION"
    OFFLINE = "OFFLINE"
    TIMEOUT = "TIMEOUT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_IN_STATE = "ALREADY_IN_STATE"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    INVALID_REQUEST = "INVALID_REQUEST"
    
    # Phase 2 Error Codes
    WIFI_ADAPTER_NOT_FOUND = "WIFI_ADAPTER_NOT_FOUND"
    WIFI_UNAVAILABLE = "WIFI_UNAVAILABLE"
    WIFI_OPERATION_FAILED = "WIFI_OPERATION_FAILED"
    POWER_OPERATION_FAILED = "POWER_OPERATION_FAILED"
    ACTION_UNAVAILABLE = "ACTION_UNAVAILABLE"

    # Phase 3 Error Codes
    SAFE_MODE_BLOCKED = "SAFE_MODE_BLOCKED"
    APP_NOT_ALLOWED = "APP_NOT_ALLOWED"
    APP_DISABLED = "APP_DISABLED"
    APP_NOT_FOUND = "APP_NOT_FOUND"
    PROTECTED_PROCESS = "PROTECTED_PROCESS"

    # Phase 4 File & Folder Error Codes
    PATH_TRAVERSAL_DETECTED = "PATH_TRAVERSAL_DETECTED"
    PROTECTED_DIRECTORY = "PROTECTED_DIRECTORY"
    ROOT_NOT_FOUND = "ROOT_NOT_FOUND"
    FILE_EXISTS = "FILE_EXISTS"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    TRANSFER_CANCELLED = "TRANSFER_CANCELLED"
    TRANSFER_FAILED = "TRANSFER_FAILED"


class AllowedAction(str, Enum):
    # Phase 1 Allowed Actions
    GET_STATUS = "GET_STATUS"
    GET_SYSTEM_INFO = "GET_SYSTEM_INFO"
    GET_NETWORK_INFO = "GET_NETWORK_INFO"
    GET_AGENT_INFO = "GET_AGENT_INFO"
    GET_CAPABILITIES = "GET_CAPABILITIES"
    
    # Phase 2 Actions
    WIFI_STATUS = "WIFI_STATUS"
    WIFI_ON = "WIFI_ON"
    WIFI_OFF = "WIFI_OFF"
    LOCK_PC = "LOCK_PC"
    RESTART_PC = "RESTART_PC"
    SHUTDOWN_PC = "SHUTDOWN_PC"
    
    # Phase 3 Actions
    GET_RUNNING_APPLICATIONS = "GET_RUNNING_APPLICATIONS"
    START_ALLOWED_APP = "START_ALLOWED_APP"
    STOP_ALLOWED_APP = "STOP_ALLOWED_APP"
    
    # Phase 4 Actions
    GET_DIRECTORY = "GET_DIRECTORY"
    GET_FILE_METADATA = "GET_FILE_METADATA"
    CREATE_FOLDER = "CREATE_FOLDER"
    RENAME_PATH = "RENAME_PATH"
    DELETE_PATH = "DELETE_PATH"
    START_UPLOAD = "START_UPLOAD"
    START_DOWNLOAD = "START_DOWNLOAD"
    CANCEL_TRANSFER = "CANCEL_TRANSFER"
    
    # Phase 5+ Placeholder Actions
    GET_DISK_INFO = "GET_DISK_INFO"
