from pydantic import BaseModel, Field
from typing import Optional


class AgentInfo(BaseModel):
    agent_id: str = Field(..., description="Unique ID generated by the Agent")
    computer_name: str = Field(..., description="Hostname/Display name of the PC")
    ip_address: str = Field(..., description="Local IP address of the PC")
    port: int = Field(8765, description="Agent API server listening port")
    os_name: str = Field("Windows", description="Operating system name")
    os_version: str = Field("", description="Detailed OS version")
    agent_version: str = Field("1.0.0", description="Agent software version")
    installation_id: str = Field("", description="Unique installation GUID")
    pairing_status: str = Field("UNPAIRED", description="PAIRED or UNPAIRED")
